### ISSUE TITLE
we got failed when we running delete service kubernetes-plugin-2.0.3

### ISSUE THREAD

**Issue by buluxan** [rundeck-plugins/kubernetes#101]
hi there ,

i created job   Kubernetes / Service / Delete   it was succesfully delete the service on the kubernetes but  when i checked on the rundeck it seem like failure

here's the logs :
============

Traceback (most recent call last):
  File "/var/lib/rundeck/libext/cache/kubernetes-plugin-2.0.3/service-delete.py", line 48, in <module>
    main()
  File "/var/lib/rundeck/libext/cache/kubernetes-plugin-2.0.3/service-delete.py", line 40, in main
    print(common.parseJson(api_response))
  File "/var/lib/rundeck/libext/cache/kubernetes-plugin-2.0.3/common.py", line 258, in parseJson
    return json.dumps(obj, cls=ObjectEncoder)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/var/lib/rundeck/libext/cache/kubernetes-plugin-2.0.3/common.py", line 254, in default
    return {k.lstrip('_'): v for k, v in vars(obj).items()}
TypeError: vars() argument must have __dict__ attribute
Failed: NonZeroResultCode: Script result code was: 1

<img width="1130" alt="Screen Shot 2021-04-05 at 15 07 17" src="https://user-images.githubusercontent.com/7418412/113552693-b1245400-9620-11eb-9749-709db8685635.png">

**Comment by blbradley** [comment]
do you have a resolution to this?

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
