### ISSUE TITLE
Character output from script cause error in plugin

### ISSUE THREAD

**Issue by Stephen-Bo** [rundeck-plugins/kubernetes#108]
Because there is  character " é " in kubernetes the rundeck plugin is failing

Error : 

Traceback (most recent call last):
--
13:19:41 | &nbsp; | File "/home/rundeck/libext/cache/kubernetes-plugin-1.0.16/job-wait.py", line 113, in &lt;module&gt;
13:19:41 | &nbsp; | main()
13:19:41 | &nbsp; | File "/home/rundeck/libext/cache/kubernetes-plugin-1.0.16/job-wait.py", line 109, in main
13:19:41 | &nbsp; | wait()
13:19:41 | &nbsp; | File "/home/rundeck/libext/cache/kubernetes-plugin-1.0.16/job-wait.py", line 77, in wait
13:19:41 | &nbsp; | print(line)
13:19:41 | &nbsp; | UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 110: ordinal not in range(128)
13:19:41 | &nbsp; | Failed: NonZeroResultCode: Script result code was: 1
13:19:41 | &nbsp; | Execution failed: 2151066 in project XXX: [Workflow result: , step failures: {4=Dispatch failed on 1 nodes: [rundeck-xxxx-xxxx: NonZeroResultCode: Script result code was: 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {rundeck-xxxx-xxxx=[NonZeroResultCode: Script result code was: 1 + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
