### ISSUE TITLE
client.Configuration.set_default AttributeError: 'function' object has no attribute 'set_default'

### ISSUE THREAD

**Issue by ecarrascos** [rundeck-plugins/kubernetes#3]
When attempting to run a Kubernetes / Job / Create, with the following project's and  job authentication settings:

project:

project.nodeCache.enabled=false
project.plugin.NodeExecutor.Kubernetes-node-executor.config_file=/var/lib/rundeck/.kube/config
project.plugin.NodeExecutor.Kubernetes-node-executor.shell=/bin/bash
project.plugin.NodeExecutor.Kubernetes-node-executor.token=keys/k8s/rundeck-token-nwkmp
project.plugin.NodeExecutor.Kubernetes-node-executor.url=k8s.mycluster.com

job:
  - name: CONFIG_PATH
    required: true
    value: s3://pathtofile.yaml
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        api_version: batch/v1
        container_image: 1234.mycontainer
        container_name: my-data-export
        debug: 'true'
        environments: CONFIG_PATH=${option.CONFIG_PATH}
        image_pull_policy: Always
        name: my-data-export-service
        namespace: default
        token: keys/k8s/rundeck-token-nwkmp
        url: k8s.mycluster.com
        verify_ssl: 'false'
      nodeStep: true
      type: Kubernetes-Create-Job
    keepgoing: true
    strategy: node-first

it fails as with an error that points to the client configuration set on the plugin:

[Kubernetes-Create-Job] executing: [python, -u, /var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.4/job-create.py]

DEBUG: kubernetes-model-source: Log level configured for DEBUG
Traceback (most recent call last):
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.4/job-create.py", line 208, in <module>
main()
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.4/job-create.py", line 132, in main
 common.connect()
File "/var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.4/common.py", line 60, in connect
client.Configuration.set_default(configuration)
 AttributeError: 'function' object has no attribute 'set_default'
 [Kubernetes-Create-Job]: result code: 1
 Failed: NonZeroResultCode: Script result code was: 1

**Comment by ltamaster** [comment]
Hey @ecarrascos ,

I tested this and it worked for me, maybe we should ask about python and kubernetes SDK versions.

Luis

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
