### ISSUE TITLE
Can't Delete Job

### ISSUE THREAD

**Issue by majgis** [rundeck-plugins/kubernetes#8]
plugin version: 1.0.5

I had success creating a job using this plugin. :fireworks: :tada: :balloon: 
Unfortunately, I'm unable to delete a job using either `Kubernetes / Generic / Delete` or `Kubernetes / Job / Delete` (also `Kubernetes / Job / Re-Run` fails on create step):

Using `Kubernetes / Generic / Delete:` results in `TypeError: delete_namespaced_job() takes exactly 4 arguments (3 given)`
```
17:40:05 |   |   | 1: Workflow step executing: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
17:40:05 |   |   | preparing for sequential execution on 1 nodes
17:40:05 |   |   | Executing command on node: localhost, NodeEntryImpl{tags=[], attributes={nodename=localhost, hostname=localhost, osFamily=unix, osVersion=4.15.0-23-generic, osArch=amd64, description=Rundeck server node, osName=Linux, username=rundeck, tags=}, project='null'}
17:40:05 |   |   | [workflow] beginExecuteNodeStep(localhost): NodeDispatch: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
17:40:05 |   |   | [Kubernetes-Delete] step started, config: {name=helloworld, namespace=default, debug=true, verify_ssl=false, type=Job}
17:40:05 |   |   | [Kubernetes-Delete] executing: [python, -u, /var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.5/delete.py]
17:40:05 |   |   | DEBUG: kubernetes-model-source: Log level configured for DEBUG
17:40:05 |   |   | Traceback (most recent call last):
17:40:05 |   |   | File "/var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.5/delete.py", line 116, in <module>
17:40:05 |   |   | main()
17:40:05 |   |   | File "/var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.5/delete.py", line 68, in main
17:40:05 |   |   | pretty="true")
17:40:05 |   |   | TypeError: delete_namespaced_job() takes exactly 4 arguments (3 given)
17:40:05 |   |   | [Kubernetes-Delete]: result code: 1
17:40:05 |   |   | Failed: NonZeroResultCode: Script result code was: 1
```

Using `Kubernetes / Job / Delete` reports success:

```
17:32:35 |   |   | 1: Workflow step executing: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
-- | -- | -- | --
17:32:35 |   |   | preparing for sequential execution on 1 nodes
17:32:35 |   |   | Executing command on node: localhost, NodeEntryImpl{tags=[], attributes={nodename=localhost, hostname=localhost, osFamily=unix, osVersion=4.15.0-23-generic, osArch=amd64, description=Rundeck server node, osName=Linux, username=rundeck, tags=}, project='null'}
17:32:35 |   |   | [workflow] beginExecuteNodeStep(localhost): NodeDispatch: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
17:32:35 |   |   | [Kubernetes-Delete-Job] step started, config: {name=helloworld, namespace=default, debug=true, verify_ssl=false}
17:32:35 |   |   | [Kubernetes-Delete-Job] executing: [python, -u, /var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.5/job-delete.py]
17:32:35 |   |   | DEBUG: kubernetes-service-delete: Log level configured for DEBUG
17:32:35 |   |   | Deployment deleted '{u'completionTime': u'2018-06-21T23:25:57Z', u'conditions': [{u'status': u'True', u'lastProbeTime': u'2018-06-21T23:25:57Z', u'type': u'Complete', u'lastTransitionTime': u'2018-06-21T23:25:57Z'}], u'succeeded': 1, u'startTime': u'2018-06-21T23:25:53Z'}'
17:32:35 |   |   | [Kubernetes-Delete-Job]: result code: 0
```
but all future create attempts result in failure:

```

16:52:17 |   | 2. Kubernetes / Job / Create | [workflow] Begin step: 2,NodeDispatch
-- | -- | -- | --
16:52:17 |   |   | 2: Workflow step executing: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
16:52:17 |   |   | preparing for sequential execution on 1 nodes
16:52:17 |   |   | Executing command on node: localhost, NodeEntryImpl{tags=[], attributes={nodename=localhost, hostname=localhost, osFamily=unix, osVersion=4.15.0-23-generic, osArch=amd64, description=Rundeck server node, osName=Linux, username=rundeck, tags=}, project='null'}
16:52:17 |   |   | [workflow] beginExecuteNodeStep(localhost): NodeDispatch: StepExecutionItem{type='NodeDispatch', keepgoingOnSuccess=false, hasFailureHandler=false}
16:52:17 |   |   | [Kubernetes-Create-Job] step started, config: {debug=false, container_name=alp, verify_ssl=false, image_pull_policy=Always, name=helloworld, namespace=default, container_command=echo hello k8s, api_version=batch/v1, job_restart_policy=Never, container_image=alpine}
16:52:17 |   |   | [Kubernetes-Create-Job] executing: [python, -u, /var/lib/rundeck/libext/cache/kubernetes-plugin-1.0.5/job-create.py]
16:52:17 |   |   | ERROR: kubernetes-model-source: Exception creating job: (409)
16:52:17 |   |   | Reason: Conflict
16:52:17 |   |   | HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 21 Jun 2018 22:52:17 GMT', 'Content-Length': '245', 'Content-Type': 'application/json'})
16:52:17 |   |   | HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"object is being deleted: jobs.batch \"helloworld\" already exists","reason":"AlreadyExists","details":{"name":"helloworld","group":"batch","kind":"jobs"},"code":409}
16:52:17 |   |   |  
16:52:17 |   |   |  
16:52:17 |   |   |  
16:52:17 |   |   | [Kubernetes-Create-Job]: result code: 1
```

Using kubectl, the job is deleted without issue (same config used by rundeck plugin):
```
[root@kubernetes ~]# kubectl get jobs
NAME         DESIRED   SUCCESSFUL   AGE
helloworld   1         1            3m
[root@kubernetes ~]# kubectl describe jobs helloworld
Name:           helloworld
Namespace:      default
Selector:       controller-uid=fca539a8-75a4-11e8-88e2-fa163eaa4323
Labels:         controller-uid=fca539a8-75a4-11e8-88e2-fa163eaa4323
                job-name=helloworld
Annotations:    <none>
Parallelism:    1
Completions:    1
Start Time:     Thu, 21 Jun 2018 16:46:50 -0600
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=fca539a8-75a4-11e8-88e2-fa163eaa4323
           job-name=helloworld
  Containers:
   alp:
    Image:  alpine
    Port:   <none>
    Command:
      echo
      hello
      k8s
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  6m    job-controller  Created pod: helloworld-rzdj8
[root@kubernetes ~]# kubectl delete jobs helloworld
job "helloworld" deleted
[root@kubernetes ~]# kubectl describe jobs helloworld
Error from server (NotFound): jobs.batch "helloworld" not found
```

**Comment by majgis** [comment]
This issue explains the problem with `Kubernetes / Job / Delete` and provides a solution:

I modified this line:
https://github.com/rundeck-plugins/kubernetes/blob/master/contents/job-delete.py#L32

to be:

    body = client.V1DeleteOptions(api_version='v1',kind="DeleteOptions",propagation_policy="Background")

and jobs are now successfully being deleted.

**Comment by majgis** [comment]
Actually, that is leaving pods behind, so it makes sense that kubectl does it the right way by deleting the pod and job separately:
```
$ kubectl get jobs   
NAME      DESIRED   SUCCESSFUL   AGE
rundeck   1         1            14s

$ kubectl get pods -a
NAME            READY     STATUS      RESTARTS   AGE
rundeck-gp4lm   0/1       Completed   0          2h
rundeck-t5zxj   0/1       Completed   0          7m
rundeck-xg4sf   0/1       Completed   0          6m
rundeck-zrkj2   0/1       Completed   0          2h

```

**Comment by ltamaster** [comment]
Hi @majgis,
Thanks for the feedback

I fixed the  `Kubernetes / Generic / Delete`.
Also on `Kubernetes / Job / Delete` I removed the pods that the job created.

Please let me know if those changes worked for you.

Luis

**Comment by majgis** [comment]
Thank you!  I'll test this change as soon as I can.

**Comment by majgis** [comment]
I installed 1.0.6 of this plugin, and delete worked as expected.  Thank you!

**Comment by ltamaster** [comment]
Great, thanks @majgis
