### ISSUE TITLE
kubernetes module v12.0.0 not working

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck-plugins/kubernetes#85]
This error:
```
Traceback (most recent call last):
  File "/home/jpla/rundeck/rd.repo/pro/3.3.4/libext/cache/kubernetes-plugin-2.0.1/pods-resource-model.py", line 262, in <module>
    main()
  File "/home/jpla/rundeck/rd.repo/pro/3.3.4/libext/cache/kubernetes-plugin-2.0.1/pods-resource-model.py", line 219, in main
    ret = v1.list_pod_for_all_namespaces(
  File "/home/jpla/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16864, in list_pod_for_all_namespaces
    return self.list_pod_for_all_namespaces_with_http_info(**kwargs)  # noqa: E501
  File "/home/jpla/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16967, in list_pod_for_all_namespaces_with_http_info
    return self.api_client.call_api(
  File "/home/jpla/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/jpla/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/jpla/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/jpla/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/jpla/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 654, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 274, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 228, in _new_conn
    conn = self.ConnectionCls(
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 115, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
[2020-10-21T10:54:51,579] ERROR resources.ExceptionCatchingResourceModelSource - [ResourceModelSource: 2.source (kubernetes-resource-model), project: mysql] 
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: failed to execute: /home/jpla/rundeck/rd.repo/pro/3.3.4/libext/cache/kubernetes-plugin-2.0.1/pods-resource-model.py: Script execution failed with result: 1
	at com.dtolabs.rundeck.core.resources.ScriptPluginResourceModelSource.getNodes(ScriptPluginResourceModelSource.java:82) ~[rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:58) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.DelegateResourceModelSource.getNodes(DelegateResourceModelSource.java:35) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:139) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:359) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:58) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source) [rundeck-core-3.3.4-20201007.jar!/:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44) [classes!/:?]
	at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source) [classes!/:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:313) [classes!/:?]
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) [groovy-2.5.6.jar!/:2.5.6]
	at com.codahale.metrics.Timer.time(Timer.java:104) [metrics-core-4.0.7.jar!/:4.0.7]
	at sun.reflect.GeneratedMethodAccessor560.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:188) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) [groovy-2.5.6.jar!/:2.5.6]
	at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:60) [metricsweb-3.3.4-20201007.jar!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:179) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:103) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService$_loadNodes_closure6.doCall(NodeService.groovy:320) [classes!/:?]
	at rundeck.services.NodeService$_loadNodes_closure6.doCall(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.run(Closure.java:486) [groovy-2.5.6.jar!/:2.5.6]
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:275) [spring-core-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Script execution failed with result: 1
	at com.dtolabs.rundeck.core.resources.ScriptResourceUtil.executeScript(ScriptResourceUtil.java:147) ~[rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ScriptPluginResourceModelSource.getNodes(ScriptPluginResourceModelSource.java:68) ~[rundeck-core-3.3.4-20201007.jar!/:?]
	... 61 more
```
**WORKAROUND**
pip3 install kubernetes==11.0.0

**Comment by jbanda15** [comment]
Same here.
Rundeck Enterprise 3.3.4 
kubernetes==12.0.0

`Traceback (most recent call last):
  File "/home/jason/Rundeck/versions/3/3.3/3.3.4/libext/cache/kubernetes-plugin-2.0.1/pods-resource-model.py", line 262, in <module>
    main()
  File "/home/jason/Rundeck/versions/3/3.3/3.3.4/libext/cache/kubernetes-plugin-2.0.1/pods-resource-model.py", line 219, in main
    ret = v1.list_pod_for_all_namespaces(
  File "/home/jason/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16864, in list_pod_for_all_namespaces
    return self.list_pod_for_all_namespaces_with_http_info(**kwargs)  # noqa: E501
  File "/home/jason/.local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16967, in list_pod_for_all_namespaces_with_http_info
    return self.api_client.call_api(
  File "/home/jason/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/jason/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/jason/.local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/jason/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/jason/.local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 654, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 274, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 228, in _new_conn
    conn = self.ConnectionCls(
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 115, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
[2020-10-21T18:14:46,727] ERROR resources.ExceptionCatchingResourceModelSource - [ResourceModelSource: 2.source (kubernetes-resource-model), project: k8s] 
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: failed to execute: /home/jason/Rundeck/versions/3/3.3/3.3.4/libext/cache/kubernetes-plugin-2.0.1/pods-resource-model.py: Script execution failed with result: 1
	at com.dtolabs.rundeck.core.resources.ScriptPluginResourceModelSource.getNodes(ScriptPluginResourceModelSource.java:82) ~[rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:58) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.DelegateResourceModelSource.getNodes(DelegateResourceModelSource.java:35) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:139) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:359) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:58) [rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source) [rundeck-core-3.3.4-20201007.jar!/:?]
	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44) [classes!/:?]
	at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source) [classes!/:?]
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:313) [classes!/:?]
	at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) [groovy-2.5.6.jar!/:2.5.6]
	at com.codahale.metrics.Timer.time(Timer.java:104) [metrics-core-4.0.7.jar!/:4.0.7]
	at sun.reflect.GeneratedMethodAccessor518.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:188) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) [groovy-2.5.6.jar!/:2.5.6]
	at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:60) [metricsweb-3.3.4-20201007.jar!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:179) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:143) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:103) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService.loadNodes(NodeService.groovy:325) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:94) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy) [classes!/:?]
	at rundeck.services.NodeService$3.methodMissing(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService$3.invokeMethod(NodeService.groovy) [classes!/:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:337) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176) [groovy-2.5.6.jar!/:2.5.6]
	at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy:147) [classes!/:?]
	at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-2.5.6.jar!/:2.5.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:405) [groovy-2.5.6.jar!/:2.5.6]
	at groovy.lang.Closure.call(Closure.java:399) [groovy-2.5.6.jar!/:2.5.6]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:275) [spring-core-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Script execution failed with result: 1
	at com.dtolabs.rundeck.core.resources.ScriptResourceUtil.executeScript(ScriptResourceUtil.java:147) ~[rundeck-core-3.3.4-20201007.jar!/:?]
	at com.dtolabs.rundeck.core.resources.ScriptPluginResourceModelSource.getNodes(ScriptPluginResourceModelSource.java:68) ~[rundeck-core-3.3.4-20201007.jar!/:?]
	... 79 more
[2020-10-21T18:14:46,730] WARN  resources.LoggingResourceModelSourceCache - [ResourceModelSource: 2.source (kubernetes-resource-model), project: k8s] Returning cached model data`

**Comment by jtobard** [comment]
Labeling it as `enhancement` because is documented that this only works with v11:
https://github.com/rundeck-plugins/kubernetes/blob/master/README.md#requirements

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
